name = "simone-jovita-api"
main = "src/worker.ts"
compatibility_date = "2026-09-28"

[[d1_databases]]
binding = "DB"
database_name = "simone-jovita-db"
database_id = "f17132c9-0fe4-48dd-acab-8388d9d03542"

[vars]
ENVIRONMENT = "production"

[assets]
directory = "./dist"
binding = "ASSETS"
